### ISSUE TITLE
Install occassionally fails due to keyring issues

### ISSUE THREAD

**Issue by ghost** [kontextwechsel/arch-linux-installation#16]
Example:

`error: glibc: signature from "Frederik Schwan <frederik.schwan@linux.com>" is unknown trust `

I manually added pacman -S archlinux-keyring to the installation script and fired the procedure again. This time the installation was successful. Maybe we should always install the keyring to avoid such problems in the first place.

**Comment by kontextwechsel** [comment]
Fixed with commit [Synchronize Arch Linux PGP keyring](https://github.com/kontextwechsel/arch-linux-installation/commit/c8eeee4c127dbe1d3263785e0071f7c3c4491b12).
