### ISSUE TITLE
Different password for user and disk encryption

### ISSUE THREAD

**Issue by ghost** [kontextwechsel/arch-linux-installation#3]
By now the installation routine asks for a password that will be used for both user and disk encryption. 

We should use different passwords for that.

**Comment by ghost** [comment]
Implementation done: https://github.com/kontextwechsel/arch-linux-installation/commit/8f6f4f873833c6b7e55a9d86b83afc4bd069b2b5

I'll open a PR once tested.

**Comment by kontextwechsel** [comment]
Merged pull request.
