### ISSUE TITLE
Before install: drop existing partitions

### ISSUE THREAD

**Issue by ghost** [kontextwechsel/arch-linux-installation#4]
In order to avoid collisions between newly generated partition tables, device names and UUIDs, mountpoints etc. it is strongly recommended to wipe the target installation disk or at least dropping existing partitioning tables.

**Comment by kontextwechsel** [comment]
Fixed with commit [Exit if creating partition table fails and unmount filesystems](https://github.com/kontextwechsel/arch-linux-installation/commit/752194da1760993210aec9eb064ac6457ed882cb).
