### ISSUE TITLE
After install: remove mountpoints

### ISSUE THREAD

**Issue by ghost** [kontextwechsel/arch-linux-installation#5]
To avoid any strange side effects after successfully installing arch, we should umount the following locations:

`/mnt`
`/mnt/boot`

**Comment by kontextwechsel** [comment]
Fixed with commit [Exit if creating partition table fails and unmount filesystems](https://github.com/kontextwechsel/arch-linux-installation/commit/752194da1760993210aec9eb064ac6457ed882cb).
